### ISSUE TITLE
Gaudi 36.7 fails to compile against fmt 9.1.0

### ISSUE THREAD

**Issue by wdconinc** [key4hep/Gaudi#1]
- OS version: ubuntu 22.04
 - Compiler version: gcc 12.1.0
 - Package version: gaudi 36.7
 - Reproduced by: `spack install gaudi@36.7 ^fmt@9.1.0` on up-to-date spack develop
 - Output: see below

The latest version of gaudi fails to compile against the latest version of fmt. This is apparent in the current [develop branch](https://github.com/spack/spack/commit/9e0755ca3a125f6360ea84223630a05363536101) of spack, where fmt 9.0.0 and 9.1.0 have landed a few days ago. The issue seems to be due to a missing formatter for StatEntity e.g. [here](https://github.com/key4hep/Gaudi/blob/7f57a304512b51aa17f6d613f22a44a95077a669/GaudiKernel/src/Lib/Stat.cpp#L95), but I have not looked into this in more detail.

See alo https://github.com/spack/spack/pull/32699.

```console
In file included from /opt/software/linux-ubuntu22.04-skylake/gcc-12.1.0/fmt-9.1.0-3gig6ivmaup62mkfcwlezcn2kniykdpu/include/fmt/format.h:48,
                 from /home/wdconinc/.spack/stage/spack-stage-gaudi-36.7-4mk4pnq4lyxy3cwgkmfx73257umgluz5/spack-src/GaudiKernel/src/Lib/Stat.cpp:14:
/opt/software/linux-ubuntu22.04-skylake/gcc-12.1.0/fmt-9.1.0-3gig6ivmaup62mkfcwlezcn2kniykdpu/include/fmt/core.h: In instantiation of 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = StatEntity&]':
/opt/software/linux-ubuntu22.04-skylake/gcc-12.1.0/fmt-9.1.0-3gig6ivmaup62mkfcwlezcn2kniykdpu/include/fmt/core.h:1777:29:   required from 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; type <anonymous> = fmt::v9::detail::type::custom_type; T = StatEntity&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]'
/opt/software/linux-ubuntu22.04-skylake/gcc-12.1.0/fmt-9.1.0-3gig6ivmaup62mkfcwlezcn2kniykdpu/include/fmt/core.h:1901:77:   required from 'constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {StatEntity&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {StatEntity}]'
/opt/software/linux-ubuntu22.04-skylake/gcc-12.1.0/fmt-9.1.0-3gig6ivmaup62mkfcwlezcn2kniykdpu/include/fmt/core.h:1918:31:   required from 'constexpr fmt::v9::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<Args>::type>::type ...> fmt::v9::make_format_args(Args&& ...) [with Context = basic_format_context<appender, char>; Args = {StatEntity&}]'
/opt/software/linux-ubuntu22.04-skylake/gcc-12.1.0/fmt-9.1.0-3gig6ivmaup62mkfcwlezcn2kniykdpu/include/fmt/core.h:3206:44:   required from 'std::string fmt::v9::format(format_string<T ...>, T&& ...) [with T = {StatEntity&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, StatEntity&>]'
/home/wdconinc/.spack/stage/spack-stage-gaudi-36.7-4mk4pnq4lyxy3cwgkmfx73257umgluz5/spack-src/GaudiKernel/src/Lib/Stat.cpp:95:50:   required from here
/opt/software/linux-ubuntu22.04-skylake/gcc-12.1.0/fmt-9.1.0-3gig6ivmaup62mkfcwlezcn2kniykdpu/include/fmt/core.h:1757:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1757 |       formattable,
      |       ^~~~~~~~~~~
/opt/software/linux-ubuntu22.04-skylake/gcc-12.1.0/fmt-9.1.0-3gig6ivmaup62mkfcwlezcn2kniykdpu/include/fmt/core.h:1757:7: note: 'formattable' evaluates to false
make[2]: *** [GaudiKernel/CMakeFiles/GaudiKernel.dir/build.make:1367: GaudiKernel/CMakeFiles/GaudiKernel.dir/src/Lib/Stat.cpp.o] Error 1
make[2]: Leaving directory '/home/wdconinc/.spack/stage/spack-stage-gaudi-36.7-4mk4pnq4lyxy3cwgkmfx73257umgluz5/spack-build-4mk4pnq'
make[1]: *** [CMakeFiles/Makefile2:1590: GaudiKernel/CMakeFiles/GaudiKernel.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by wdconinc** [comment]
@vvolkl Feel free to forward or repost on to the Gaudi gitlab.cern.ch server where I have no write access.

**Comment by vvolkl** [comment]
Done: https://gitlab.cern.ch/gaudi/Gaudi/-/issues/239

**Comment by tmadlener** [comment]
Hi @wdconinc, is this the complete patch to fix this with `fmt@9:`? Then I would also forward this to the Gaudi repo

**Comment by wdconinc** [comment]
That is the only change I needed to apply with the configuration I used. It is possible that there are other instances of `fmt` that need to be addressed (I don't think I compiled the examples). The fix is also something that should be possible to turn into an a generic solution with `enable_if_t` on the combination of `! has_formatter<T>` and `has_output_operator`, something like:
```cpp
template <typename T, typename = void>
struct has_output_operator : std::false_type {};

template <typename T>
struct has_output_operator<T, std::void_t<decltype(std::cout << std::declval<T>())>> : std::true_type {};

template <typename T, typename Char, typename Context>
struct fmt::formatter<
    T,
    std::enable_if_t<
        !fmt::has_formatter<T, Context>::value &&
        has_output_operator<T>::value,
        Char
    >
> : fmt::ostream_formatter {};
```
(but I couldn't get this to work due to the `Context` part).

**Comment by tmadlener** [comment]
In principle it is possible to get rid of the 'Char' and 'Context' template parameters by introducing `has_fmt_support` helper structs essentially analogous to the `has_output_operator`, and then moving the `enable_if_t` one level further up
```cpp
template<typename T>
struct fmt::formatter<std::enable_if_t<has_output_operator::value && !has_fmt_support<T>::value,
                                       T>
                     > : fmt::ostream_formatter {};
```

However, this doesn't compile either, due to: `error: template parameters not deducible in partial specialization`.

I am not entirely sure whether the "generic" partial template spezializtion that would be necessary here, is in fact possible. At least I currently don't see a SFINAE friendly version at least.

Anyhow, I will forward the above patch and then we will see where CI fails, I suppose.

**Comment by tmadlener** [comment]
"upstream" merge request: https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1409

**Comment by wdconinc** [comment]
Thanks for submitting upstream.

> `error: template parameters not deducible in partial specialization`

Yes, that was the same error that I got.

I mostly got interested in a generic solution after the fourth time I had to extend a formatter based on the existing ostream operator...

**Comment by tmadlener** [comment]
The fix has been merged upstream so this should be fixed.
